INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA01LABOCA','WLink 01 La Boca', 'La Boca','C:\\Program Files (x86)\\WLink 01 La Boca\\EMA01LAB');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA02MORON','WLink 02 Moron', 'Moron', 'C:\\Program Files (x86)\\WLink 02 Moron\\EMA02MOR');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA03MERLO', 'WLink 03 Merlo', 'Merlo', 'C:\\Program Files (x86)\\WLink 03 Merlo\\EMA03MER');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA04MARCOSPAZ', 'WLink 04 Marcos Paz', 'Marcos Paz', 'C:\\Program Files (x86)\\WLink 04 Marcos Paz\\EMA04MAR');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA05LANUS', 'WLink 05 Lanus', 'Lanus', 'C:\\Program Files (x86)\\WLink 05 Lanus\\EMA05LAN');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA06AVELLANEDA', 'WLink 06 Avellaneda', 'Avellaneda', 'C:\\Program Files (x86)\\WLink 06 Avellaneda\\EMA06AVE');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA07ALTEBROWN', 'WLink 07 Alte  Brown', 'Alte Brown', 'C:\\Program Files (x86)\\WLink 07 Alte Brown\\EMA07ALT');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA08ESTEBANECHEVERRIA', 'WLink 08 Esteban Echeverria', 'Esteban Echeverria', 'C:\\Program Files (x86)\\WLink 08 Esteban Echeverria\\EMA08EST');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA09LOMASDEZAMORA', 'WLink 09 Lomas de Zamora', 'Lomas de Zamora', 'C:\\Program Files (x86)\\WLink 09 Lomas de Zamora\\EMA09LOM');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA10SANVICENTE', 'WLink 10 San Vicente', 'San Vicente', 'C:\\Program Files (x86)\\WLink 10 San Vicente\\EMA10SAN');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA11PTEPERON', 'WLink 11 Pte Peron', 'Pte Peron', 'C:\\Program Files (x86)\\WLink 11 Pte Peron\\EMA11PTE');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA12LASHERAS', 'WLink 12 Las Heras', 'Las Heras', 'C:\\Program Files (x86)\\WLink 12 Las Heras\\EMA12LAS');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA13LAMATANZA', 'WLink 13 La Matanza', 'La Matanza', 'C:\\Program Files (x86)\\WLink 13 La Matanza\\EMA13LAM');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA14EZEIZA', 'WLink 14 Ezeiza', 'Ezeiza', 'C:\\Program Files (x86)\\WLink 14 Ezeiza\\EMA14EZE');
INSERT IGNORE INTO `ta_ams_station` (`station_id`,`name`,`location`,`db_path`) VALUES ('EMA15CANUELAS', 'WLink 15 Canuelas', 'Canuelas', 'C:\\Program Files (x86)\\WLink 15 Canuelas\\EMA15CAN');
